name: vtd be java dev

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - vtd-be-java-dev


jobs:
  setup-build-publish-deploy:
    environment: DEV
    env:
      GKE_CLUSTER: vitadairy-k8s-dev
      # GCP_PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
      GKE_ZONE: asia-southeast1-b
      DEPLOYMENT_NAME: vitadairy-java-loyalty-be
      GAR_HOST: asia-southeast1-docker.pkg.dev
      GAR_NAME: vtd-dev
      IMAGE_NAME: vitadairy-java-loyalty-be
      IMAGE_TAG: ${{ github.sha }}
      SPRING_PROFILES_ACTIVE: ${{ vars.SPRING_PROFILES_ACTIVE }}
      
    name: Setup build publish deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SH
        run: echo ${{ env.SPRING_PROFILES_ACTIVE }}
