name: VTD BE PPAP

on:
  workflow_dispatch:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - vtd-trigger
      - v*

env:
  # TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  # TELEGRAM_GROUP_ID: ${{ vars.TELEGRAM_GROUP_ID}}
  # TELEGRAM_TOPIC_ID: ${{ vars.TELEGRAM_TOPIC_ID}}
  REF_NAME: ${{ github.event.client_payload.ref_name}}
  TRIGGERING_ACTOR: ${{ github.event.client_payload.triggering_actor}}

jobs:
  pre-deployment:
    name: Pre Deployment
    runs-on: ubuntu-latest
    # outputs:
    #   matrix: ${{ steps.set-matrix.outputs.value }}
    #   message-information: ${{ steps.get-message-information.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.VTD_REPOSITORY_SOURCE }}
          token: ${{ secrets.GH_PAT }}
          ref: ${{ github.event.client_payload.ref_name}}

  build-and-check:
    name: Build and check ${{ matrix.name }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [pre-deployment]
    strategy:
      matrix:
        include:
          # - service: gift
          #   name: gift service
          - service: order
            name: order service
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.VTD_REPOSITORY_SOURCE }}
          token: ${{ secrets.GH_PAT }}
          ref: ${{ github.event.client_payload.ref_name}}
          path: source

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.VTD_REPOSITORY_TARGET }}${{ matrix.service }}
          token: ${{ secrets.GH_PAT }}
          ref: main
          path: target

      - name: Setup java 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Remove the rest
        working-directory: source/${{ secrets.SERVICE_PACKAGE_PATH }}
        run: rm -rf loyalty

      - name: Build and package project
        working-directory: source
        run: mvn -f pom.xml clean package -q

      - name: Check
        working-directory: target
        run: ls -la && git status

      - name: Move code to the target
        run: |
          rm -rf source/.git
          mv target/.git source/.git
          mv source/ target/
          
      - name: Check
        working-directory: target
        run: ls -la && git status
