name: VTD Banana

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - vtd-trigger
      - v*

env:
  # TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  # TELEGRAM_GROUP_ID: ${{ vars.TELEGRAM_GROUP_ID}}
  # TELEGRAM_TOPIC_ID: ${{ vars.TELEGRAM_TOPIC_ID}}
  REF_NAME: ${{ github.event.client_payload.ref_name}}
  TRIGGERING_ACTOR: ${{ github.event.client_payload.triggering_actor}}

jobs:
  pre-deployment:
    name: Pre Deployment
    runs-on: ubuntu-latest
    # outputs:
    #   matrix: ${{ steps.set-matrix.outputs.value }}
    #   message-information: ${{ steps.get-message-information.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.VTD_REPOSITORY }}
          token: ${{ secrets.GH_PAT }}
          ref: ${{ github.event.client_payload.ref_name}}